%
%  plot_rng.m
% 
%  Created: 05. Oct. 2022
%   Author: Frank Bjørnø¸
% 
%  Purpose: Read data generated by specdata.c and plot
% 
%  License:
%  
%           Copyright (C) 2022 Frank Bjørnø¸
% 
%           1. Permission is hereby granted, free of charge, to any person obtaining a copy 
%           of this software and associated documentation files (the "Software"), to deal 
%           in the Software without restriction, including without limitation the rights 
%           to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
%           of the Software, and to permit persons to whom the Software is furnished to do 
%           so, subject to the following conditions:
%         
%           2. The above copyright notice and this permission notice shall be included in all 
%           copies or substantial portions of the Software.
% 
%           3. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
%           INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
%           PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
%           HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF 
%           CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE 
%           OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%

format = '%f,%f,%f';
V = [];
sizeV = [3 inf];

%  --------------------------    Read Data    --------------------------

	%  'rng_data.dat' should be in the same directory as this MatLab file
fileID = fopen('rng_data.dat');

if fileID == -1
    disp('Error: Could not open file.')
else
    disp('File open for reading.')
    
    while ~feof(fileID)
        V = fscanf(fileID, format, sizeV);
    end
    
    closeresult = fclose(fileID);
    if closeresult == 0;
        disp ('File closed.')
    else
        disp('Could not close file.');
    end
end

	% clean up
clear closeresult fileID fmt sizeDATA

%  -----------------------     plot the data    ------------------------

f1 = figure(1);
set(gcf, 'position', [400 500 800 480]);
plot3(V(1,:), V(2,:), V(3,:), '.');

xlim([0 1]);
ylim([0 1]);
zlim([0 1]);
grid on
